services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: teamfinder_db
    ports:
      - "5436:5432"
    volumes:
      - pg_data_16:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data_16:
